# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/huizebruin-projects
# Â© Huizebruin.nl
substitutions:
  name: mmwave

esphome:
  name: ${name}
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "huizebruin-projecten.${name}"
    version: "${project_version}"
  min_version: 2024.9.0
esp8266:
  board:  d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://huizebruin/Huizebruin-projecten/esphome/mmwave.yaml

packages:
  remote_package:
    url: https://github.com/huizebruin/Huizebruin-projecten
    ref: main
    files:
      - esphome/package/basis.yaml
      - esphome/package/mmwave1.yaml
    refresh: 0d
